blogdemo/blog/urls.py
from django.urls import path, include
from . import views
from .feeds import LatestPostsFeed
app_name = 'blog'
urlpatterns = [
    path('', views.post_list_view, name='post_list_view'),
    path('tag/<slug:tag_slug>/', views.post_list_view, name='post_list_by_tag'),

    #path('', views.PostListView.as_view(), name = 'post_list_view'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('facker/', views.fakerdemo, name='facker_demo'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
]

blogdemo/blogdemo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
]

blogdemo/blog/models.py
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
# Create your models here.
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()\
            .filter(status=Post.Status.PUBLISHED)
class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status.choices,default=Status.DRAFT)
    
    tags = TaggableManager()
    objects = models.Manager()
    published = PublishedManager()
    def __str__(self):
        return self.title
        
    
    class Meta:
        ordering: ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]
    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,self.publish.month,self.publish.day,self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created'])
        ]
        def __str__(self):
            return f'Comment by {self.name} on {self.post}'

    

blogdemo/blog/forms.py
from django import forms
from .models import Comment
class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=50)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']
        

blogdemo/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm
from slugify import slugify
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from taggit.models import Tag 
from django.db.models import Count

# Create your views here.
class PostListView(ListView):
    queryset = Post.objects.all().filter(status=Post.Status.PUBLISHED)
    context_object_name = 'posts'
    paginate_by = 10
    template_name = 'blog/post/post_list.html'

def post_list_view(request, tag_slug=None):
    posts = Post.objects.all().filter(status=Post.Status.PUBLISHED)
    page_number = request.GET.get('page', 1)
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts = posts.filter(tags__in=[tag])
    paginator = Paginator(posts, 10) # 3 post per page
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except:
        posts = paginator.page(paginator.num_pages)
    template_name = 'blog/post/post_list.html'
    context = {'posts':posts, 'tag':tag}

    return render(request, template_name, context)

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, status=Post.Status.PUBLISHED,\
            slug=post,
            publish__year=year,
            publish__month=month,
            publish__day=day
        )
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:2]
    comments = post.comments.filter(active=True)
    form = CommentForm()
    template_name = 'blog/post/post_detail.html'
    context = {'post':post,'comments':comments, 'form': form, 'similar_posts':similar_posts}
    return render(request, template_name, context)


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
                post.get_absolute_url())
            subject = f"{cd['name']} recommends you read " \
                      f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                      f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'your_account@gmail.com',
                      [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    template_name = 'blog/post/share.html'
    context = {'post':post, 'form': form, 'sent':sent}
    return render(request, template_name, context)

def fakerdemo(request):
    from faker import Faker
    fk = Faker()
    for i in range(100):
        title=fk.sentence()
        ob_post = Post.objects.create(
            title=title,
            body = fk.paragraph(nb_sentences=180),
            author_id = 1,
            status=Post.Status.PUBLISHED,
            slug= slugify(title)
        )
    context = {
        'all_new_post': ob_post
    }
    return render(request, 'blog/facker.html',context)


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post 
        comment.save()
    template = 'blog/post/comment.html'
    context={
        'post':post,
        'form': form,
        'comment': comment
    }
    return render(request, template, context)

blogdemo/blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  <link href="{% static "css/blog.css" %}" rel="stylesheet">
</head>
<body>
  <div id="content">
    {% block content %}
    {% endblock %}
  </div>
  <div id="sidebar">
    <h2>My blog</h2>
    <p>This is my blog.</p>
    I've written {% total_posts %} posts so far.
    <p>
    <p>
      <a href="{% url "blog:post_feed" %}">
        Subscribe to my RSS feed
      </a>
    </p>
      <h3>Latest posts</h3>
    {% show_latest_posts 2 %}
    </p>
    <h3>Most commented posts</h3>
    {% get_most_commented_posts 2 as most_commented_posts %}
    <ul>
      {% for post in most_commented_posts %}
        <li>
          <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>
</body>
</html>

blogdemo/blog/templates/blog/facker.html
<h1>Test</h1>
{{all_new_post}}

blogdemo/blog/templates/blog/post/comment.html
{% extends "blog/base.html" %}
{% block title %}Add a comment{% endblock %}
{% block content %}
  {% if comment %}
    <h2>Your comment has been added.</h2>
    <p><a href="{{ post.get_absolute_url }}">Back to the post</a></p>
  {% else %}
    {% include "blog/post/includes/comment_form.html" %}
  {% endif %}
{% endblock %}

blogdemo/blog/templates/blog/post/includes/comment_form.html
<h2>Add a new comment</h2>
<form action="{% url "blog:post_comment" post.id %}" method="post">
  {{ form.as_p }}
  {% csrf_token %}
  <p><input type="submit" value="Add comment"></p>
</form>

blogdemo/blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
      <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
      </li>
    {% endfor %}
  </ul>
  

blogdemo/blog/templates/blog/post/post_detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
  <h1>{{ post.title }}</h1>
  <p class="date">
    Published {{ post.publish }} by {{ post.author }}
  </p>
  {{ post.body|markdown }}
  <a href="{% url 'blog:post_list_view'%}">Home</a>
  <p>
    <a href="{% url "blog:post_share" post.id %}">
      Share this post
    </a>
  </p>
  <h2>Similar Posts: </h2>
  {% for s_post in similar_posts %}
    <p>
      <a href="{{ s_post.get_absolute_url }}">{{ s_post.title }}</a>
    </p>
    {% empty %}
      There is no similar posts.
  {% endfor %}
  {% with comments.count as total_comments %}
  <h2>
    {{ total_comments }} comment{{total_comments|pluralize}}
  </h2>
  {% endwith %}
  {% for comment in comments %}
    <div>
      <p>
        Comment {{ forloop.counter }} by {{comment.name}}
        {{ comment.created}}
      </p>
      {{ comment.body|linebreaks}}
      <hr>
    </div>
  {% empty %}
    <p>There is no comments.</p>
  {% endfor %}
  {% include "blog/post/includes/comment_form.html" %}
{% endblock %}

blogdemo/blog/templates/blog/post/post_list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}My Blog{% endblock %}
{% block content %}
  <h1>My Blog</h1>
  {% if tag %}
    <h2>Posts tagged with "{{ tag.name }}"</h2>
  {% endif %}
  {% for post in posts %}
    <h2>
      <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
      </a>
    </h2>Tags: 
    {% for tag in post.tags.all %}
      <a href="{% url "blog:post_list_by_tag" tag.slug %}">
        {{ tag.name }}
      </a>
      {% if not forloop.last %}, {% endif %}
    {% endfor %}
    <p class="date">
      Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|markdown|truncatewords_html:30 }}
  {% endfor %}
  <!-- {% include 'paginator.html' with page=posts%} this paginator for function based view-->
  {% include 'paginator.html' with page=posts%} <!-- this paginator for class based view-->
{% endblock %}

blogdemo/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}Share a post{% endblock %}
{% block content %}
  {% if sent %}
    <h1>E-mail successfully sent</h1>
    <p>
      "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
    </p>
  {% else %}
    <h1>Share "{{ post.title }}" by e-mail</h1>
    <form method="post">
        {% for field in form %}
            <div>
                {{ field.errors }}
                {{ field.label_tag }} {{ field }}
            </div>
        {% endfor %}

      
      {% csrf_token %}
      <input type="submit" value="Send e-mail">
    </form>
  {% endif %}
{% endblock %}

blogdemo/blog/templates/paginator.html
<div class="pagination">
    <span class="step-links">
      {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
      {% endif %}
      <span class="current">
        Page {{ page.number }} of {{ page.paginator.num_pages }}.
      </span>
      {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
      {% endif %}
    </span>
  </div>
  